"""Add TenantUser, MaintenanceRequest models and tenant portal fields

Revision ID: c98a9a95383d
Revises: c1d2e3f4g5h6
Create Date: 2026-04-15 13:15:34.322487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c98a9a95383d'
down_revision = 'c1d2e3f4g5h6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=1500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('invitation_token', sa.String(length=100), nullable=True),
    sa.Column('invitation_token_expires', sa.DateTime(), nullable=True),
    sa.Column('invitation_sent_at', sa.DateTime(), nullable=True),
    sa.Column('invitation_accepted_at', sa.DateTime(), nullable=True),
    sa.Column('invited_by_user_id', sa.Integer(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=100), nullable=True),
    sa.Column('password_reset_token', sa.String(length=100), nullable=True),
    sa.Column('password_reset_expires', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('password_reset_token'),
    sa.UniqueConstraint('stripe_customer_id')
    )
    with op.batch_alter_table('tenant_user', schema=None) as batch_op:
        batch_op.create_index('idx_tenant_user_active', ['company_id', 'is_active'], unique=False)
        batch_op.create_index('idx_tenant_user_company', ['company_id'], unique=False)
        batch_op.create_index('idx_tenant_user_invitation', ['invitation_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenant_user_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenant_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_tenant_user_invitation_token'), ['invitation_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_tenant_user_tenant_id'), ['tenant_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_tenant_user_uuid'), ['uuid'], unique=True)

    op.create_table('maintenance_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('tenant_user_id', sa.Integer(), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('photos', sa.JSON(), nullable=True),
    sa.Column('permission_to_enter', sa.Boolean(), nullable=True),
    sa.Column('preferred_entry_time', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('scheduled_date', sa.DateTime(), nullable=True),
    sa.Column('scheduled_time_window', sa.String(length=50), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_to_user_id', sa.Integer(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('actual_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('vendor_name', sa.String(length=150), nullable=True),
    sa.Column('vendor_phone', sa.String(length=20), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('parts_used', sa.Text(), nullable=True),
    sa.Column('tenant_feedback', sa.Text(), nullable=True),
    sa.Column('tenant_rating', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['tenant_user_id'], ['tenant_user.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maintenance_request', schema=None) as batch_op:
        batch_op.create_index('idx_maint_company_status', ['company_id', 'status'], unique=False)
        batch_op.create_index('idx_maint_priority', ['priority', 'status'], unique=False)
        batch_op.create_index('idx_maint_property', ['property_id'], unique=False)
        batch_op.create_index('idx_maint_submitted', ['submitted_at'], unique=False)
        batch_op.create_index('idx_maint_tenant', ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_request_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_request_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_request_uuid'), ['uuid'], unique=True)

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_payment_intent_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('tenant_user_id', sa.Integer(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_payment_stripe_payment_intent_id'), ['stripe_payment_intent_id'], unique=True)
        batch_op.create_foreign_key('fk_payment_tenant_user_id', 'tenant_user', ['tenant_user_id'], ['id'])

    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_portal_access', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('portal_invitation_sent', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('portal_invitation_accepted', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.drop_column('portal_invitation_accepted')
        batch_op.drop_column('portal_invitation_sent')
        batch_op.drop_column('has_portal_access')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_payment_tenant_user_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_payment_stripe_payment_intent_id'))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('tenant_user_id')
        batch_op.drop_column('stripe_payment_intent_id')

    with op.batch_alter_table('maintenance_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_request_uuid'))
        batch_op.drop_index(batch_op.f('ix_maintenance_request_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_maintenance_request_company_id'))
        batch_op.drop_index('idx_maint_tenant')
        batch_op.drop_index('idx_maint_submitted')
        batch_op.drop_index('idx_maint_property')
        batch_op.drop_index('idx_maint_priority')
        batch_op.drop_index('idx_maint_company_status')

    op.drop_table('maintenance_request')
    with op.batch_alter_table('tenant_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_user_uuid'))
        batch_op.drop_index(batch_op.f('ix_tenant_user_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_tenant_user_invitation_token'))
        batch_op.drop_index(batch_op.f('ix_tenant_user_email'))
        batch_op.drop_index(batch_op.f('ix_tenant_user_company_id'))
        batch_op.drop_index('idx_tenant_user_invitation')
        batch_op.drop_index('idx_tenant_user_company')
        batch_op.drop_index('idx_tenant_user_active')

    op.drop_table('tenant_user')
    # ### end Alembic commands ###
