"""Initial migration with all existing models

Revision ID: d6b2d5aa460c
Revises: 
Create Date: 2025-10-15 20:05:13.846034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6b2d5aa460c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('address', sa.String(length=150), nullable=True),
    sa.Column('city', sa.String(length=150), nullable=True),
    sa.Column('state', sa.String(length=150), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('website', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('company_size', sa.String(length=50), nullable=True),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('license_number', sa.String(length=100), nullable=True),
    sa.Column('established_date', sa.Date(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('logo_url', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('setting_key', sa.String(length=100), nullable=False),
    sa.Column('setting_value', sa.Text(), nullable=True),
    sa.Column('setting_type', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'setting_key', name='unique_company_setting')
    )
    op.create_table('portfolio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_uuid'), ['uuid'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=False),
    sa.Column('last_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=150), nullable=True),
    sa.Column('city', sa.String(length=150), nullable=True),
    sa.Column('state', sa.String(length=150), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('password_hash', sa.String(length=1500), nullable=False),
    sa.Column('company', sa.String(length=150), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('primary_role', sa.String(length=50), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('totp_secret', sa.String(length=32), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('totp_backup_codes', sa.Text(), nullable=True),
    sa.Column('totp_enabled_at', sa.DateTime(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('date_joined', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_uuid'), ['uuid'], unique=True)

    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.String(length=150), nullable=True),
    sa.Column('user_role', sa.String(length=20), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('endpoint', sa.String(length=200), nullable=True),
    sa.Column('http_method', sa.String(length=10), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_ip_address'), ['ip_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_resource_type'), ['resource_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_user_email'), ['user_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_user_id'), ['user_id'], unique=False)

    op.create_table('email_verification_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lease_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('template_type', sa.String(length=50), nullable=True),
    sa.Column('contract_text', sa.Text(), nullable=False),
    sa.Column('header_text', sa.Text(), nullable=True),
    sa.Column('footer_text', sa.Text(), nullable=True),
    sa.Column('default_terms', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_system_template', sa.Boolean(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('parent_template_id', sa.Integer(), nullable=True),
    sa.Column('available_merge_fields', sa.Text(), nullable=True),
    sa.Column('required_fields', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['parent_template_id'], ['lease_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lease_template', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lease_template_uuid'), ['uuid'], unique=True)

    op.create_table('password_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.String(length=1500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=150), nullable=True),
    sa.Column('city', sa.String(length=150), nullable=True),
    sa.Column('state', sa.String(length=150), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('neighborhood', sa.String(length=150), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('type', sa.String(length=150), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('lot_size', sa.Integer(), nullable=True),
    sa.Column('building_sqft', sa.Integer(), nullable=True),
    sa.Column('stories', sa.Integer(), nullable=True),
    sa.Column('parking_spaces', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('current_market_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('annual_property_tax', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('annual_insurance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('monthly_hoa_fees', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('property_manager', sa.String(length=150), nullable=True),
    sa.Column('acquisition_method', sa.String(length=50), nullable=True),
    sa.Column('property_status', sa.String(length=50), nullable=True),
    sa.Column('maintenance_priority', sa.String(length=20), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('occupancy_status', sa.String(length=20), nullable=True),
    sa.Column('status_updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_property_uuid'), ['uuid'], unique=True)

    op.create_table('expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('expense_date', sa.DateTime(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('subcategory', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('vendor', sa.String(length=100), nullable=True),
    sa.Column('receipt_url', sa.String(length=255), nullable=True),
    sa.Column('tax_deductible', sa.Boolean(), nullable=True),
    sa.Column('recurring', sa.Boolean(), nullable=True),
    sa.Column('recurring_frequency', sa.String(length=20), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('document_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('uploaded_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property_photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('caption', sa.String(length=500), nullable=True),
    sa.Column('uploaded_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=False),
    sa.Column('last_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=150), nullable=True),
    sa.Column('city', sa.String(length=150), nullable=True),
    sa.Column('state', sa.String(length=150), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_uuid'), ['uuid'], unique=True)

    op.create_table('unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('rent', sa.Integer(), nullable=True),
    sa.Column('sqft', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('air_conditioning', sa.Boolean(), nullable=True),
    sa.Column('heating_type', sa.String(length=50), nullable=True),
    sa.Column('thermostat_type', sa.String(length=50), nullable=True),
    sa.Column('appliances_included', sa.Text(), nullable=True),
    sa.Column('dishwasher', sa.Boolean(), nullable=True),
    sa.Column('garbage_disposal', sa.Boolean(), nullable=True),
    sa.Column('microwave', sa.Boolean(), nullable=True),
    sa.Column('refrigerator', sa.Boolean(), nullable=True),
    sa.Column('range_oven', sa.Boolean(), nullable=True),
    sa.Column('washer_dryer', sa.String(length=50), nullable=True),
    sa.Column('flooring_type', sa.Text(), nullable=True),
    sa.Column('ceiling_height', sa.Integer(), nullable=True),
    sa.Column('windows_type', sa.String(length=50), nullable=True),
    sa.Column('natural_light', sa.String(length=20), nullable=True),
    sa.Column('closet_space', sa.String(length=50), nullable=True),
    sa.Column('storage_units', sa.Integer(), nullable=True),
    sa.Column('balcony_patio', sa.Boolean(), nullable=True),
    sa.Column('balcony_sqft', sa.Integer(), nullable=True),
    sa.Column('parking_type', sa.String(length=50), nullable=True),
    sa.Column('parking_spaces', sa.Integer(), nullable=True),
    sa.Column('garage_type', sa.String(length=50), nullable=True),
    sa.Column('bathroom_features', sa.Text(), nullable=True),
    sa.Column('master_bath', sa.Boolean(), nullable=True),
    sa.Column('bathtub', sa.Boolean(), nullable=True),
    sa.Column('shower_type', sa.String(length=50), nullable=True),
    sa.Column('last_renovated', sa.Date(), nullable=True),
    sa.Column('condition_rating', sa.Integer(), nullable=True),
    sa.Column('recent_updates', sa.Text(), nullable=True),
    sa.Column('upcoming_maintenance', sa.Text(), nullable=True),
    sa.Column('ada_compliant', sa.Boolean(), nullable=True),
    sa.Column('wheelchair_accessible', sa.Boolean(), nullable=True),
    sa.Column('accessibility_features', sa.Text(), nullable=True),
    sa.Column('utilities_included', sa.Text(), nullable=True),
    sa.Column('utility_cost_estimate', sa.Integer(), nullable=True),
    sa.Column('energy_efficiency_rating', sa.String(length=10), nullable=True),
    sa.Column('pets_allowed', sa.Boolean(), nullable=True),
    sa.Column('pet_restrictions', sa.Text(), nullable=True),
    sa.Column('pet_fee_monthly', sa.Integer(), nullable=True),
    sa.Column('pet_deposit', sa.Integer(), nullable=True),
    sa.Column('security_features', sa.Text(), nullable=True),
    sa.Column('alarm_system', sa.Boolean(), nullable=True),
    sa.Column('secure_entry', sa.Boolean(), nullable=True),
    sa.Column('internet_included', sa.Boolean(), nullable=True),
    sa.Column('cable_ready', sa.Boolean(), nullable=True),
    sa.Column('internet_speed', sa.String(length=50), nullable=True),
    sa.Column('smart_home_features', sa.Text(), nullable=True),
    sa.Column('occupancy_status', sa.String(length=20), nullable=True),
    sa.Column('status_updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.create_index('idx_unit_bathrooms', ['bathrooms'], unique=False)
        batch_op.create_index('idx_unit_bedrooms', ['bedrooms'], unique=False)
        batch_op.create_index('idx_unit_company_id', ['company_id'], unique=False)
        batch_op.create_index('idx_unit_occupancy_status', ['occupancy_status'], unique=False)
        batch_op.create_index('idx_unit_pets_allowed', ['pets_allowed'], unique=False)
        batch_op.create_index('idx_unit_property_id', ['property_id'], unique=False)
        batch_op.create_index('idx_unit_rent', ['rent'], unique=False)
        batch_op.create_index('idx_unit_sqft', ['sqft'], unique=False)
        batch_op.create_index(batch_op.f('ix_unit_uuid'), ['uuid'], unique=True)

    op.create_table('lease',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=False),
    sa.Column('rent', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('security_deposit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pet_deposit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('late_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payment_due_date', sa.Integer(), nullable=True),
    sa.Column('grace_period_days', sa.Integer(), nullable=True),
    sa.Column('utilities_included', sa.Text(), nullable=True),
    sa.Column('parking_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('application_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('broker_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cleaning_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('administrative_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('last_month_rent', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('utility_deposits', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('storage_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('concessions', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pet_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('lease_type', sa.String(length=50), nullable=True),
    sa.Column('auto_renewal', sa.String(length=20), nullable=True),
    sa.Column('notice_period_days', sa.Integer(), nullable=True),
    sa.Column('early_termination_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_occupants', sa.Integer(), nullable=True),
    sa.Column('renewal_terms', sa.Text(), nullable=True),
    sa.Column('move_in_date', sa.Date(), nullable=True),
    sa.Column('move_out_date', sa.Date(), nullable=True),
    sa.Column('key_deposit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('move_in_inspection_notes', sa.Text(), nullable=True),
    sa.Column('move_out_inspection_notes', sa.Text(), nullable=True),
    sa.Column('lease_status', sa.String(length=20), nullable=True),
    sa.Column('status_updated_at', sa.DateTime(), nullable=True),
    sa.Column('property_manager_notes', sa.Text(), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('lease_documents', sa.Text(), nullable=True),
    sa.Column('compliance_notes', sa.Text(), nullable=True),
    sa.Column('insurance_required', sa.Boolean(), nullable=True),
    sa.Column('insurance_verified', sa.Boolean(), nullable=True),
    sa.Column('insurance_expiry_date', sa.Date(), nullable=True),
    sa.Column('background_check_status', sa.String(length=20), nullable=True),
    sa.Column('background_check_date', sa.Date(), nullable=True),
    sa.Column('credit_score', sa.Integer(), nullable=True),
    sa.Column('renewal_reminder_days', sa.Integer(), nullable=True),
    sa.Column('violation_history', sa.Text(), nullable=True),
    sa.Column('maintenance_requests', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['lease_template.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lease', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lease_uuid'), ['uuid'], unique=True)

    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lease_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('late_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['lease_id'], ['lease.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    with op.batch_alter_table('lease', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lease_uuid'))

    op.drop_table('lease')
    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unit_uuid'))
        batch_op.drop_index('idx_unit_sqft')
        batch_op.drop_index('idx_unit_rent')
        batch_op.drop_index('idx_unit_property_id')
        batch_op.drop_index('idx_unit_pets_allowed')
        batch_op.drop_index('idx_unit_occupancy_status')
        batch_op.drop_index('idx_unit_company_id')
        batch_op.drop_index('idx_unit_bedrooms')
        batch_op.drop_index('idx_unit_bathrooms')

    op.drop_table('unit')
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_uuid'))

    op.drop_table('tenant')
    op.drop_table('property_photo')
    op.drop_table('property_document')
    op.drop_table('expense')
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_property_uuid'))

    op.drop_table('property')
    op.drop_table('password_history')
    with op.batch_alter_table('lease_template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lease_template_uuid'))

    op.drop_table('lease_template')
    op.drop_table('email_verification_attempt')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_user_email'))
        batch_op.drop_index(batch_op.f('ix_audit_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_log_severity'))
        batch_op.drop_index(batch_op.f('ix_audit_log_resource_type'))
        batch_op.drop_index(batch_op.f('ix_audit_log_resource_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_ip_address'))
        batch_op.drop_index(batch_op.f('ix_audit_log_event_type'))
        batch_op.drop_index(batch_op.f('ix_audit_log_company_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_category'))

    op.drop_table('audit_log')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_uuid'))

    op.drop_table('user')
    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_uuid'))

    op.drop_table('portfolio')
    op.drop_table('company_settings')
    op.drop_table('company')
    # ### end Alembic commands ###
